### ISSUE TITLE
CLI: provide option to run all events with a given action

### ISSUE THREAD

**Issue by ethitter** [Automattic/Cron-Control#102]
`wp cron-control events run` only accepts a single ID, leaving no way to run all jobs with a given action. Like the `delete` command, `run` should accept either an ID or an action.

**Comment by WPprodigy** [comment]
I think we should just lean on WP CLI where it fits the need, especially w/ the new filters in place.

`wp cron event run example_action [--due-now]`  is good. The downside is that it'll call `_get_cron_array()` to first fetch all events, but even with thousands of events that isn't really an issue under the system.
