### ISSUE TITLE
Name Cron control transactions

### ISSUE THREAD

**Issue by sboisvert** [Automattic/Cron-Control#127]
Is it possible to add something like this:

```
if ( function_exists( 'newrelic_name_transaction' ) ) {
   newrelic_name_transaction( 'cron-control' );
} 
```
I'm guessing somewhere around https://github.com/Automattic/Cron-Control/blob/master/includes/class-events.php#L40

But I'd leave you to know the best place.

This will identify cron as a separate transaction and so we can monitor (or not) it separately.

**Comment by ethitter** [comment]
Can that be called from an action instead? I'd really rather have an action that anything can use, rather than something specific to VIP Go. While this plugin probably isn't used anywhere else, there's nothing Go-specific about it.

**Comment by ethitter** [comment]
Oh, I meant an action in the plugin. I'm open to adding those as we find need for them.

**Comment by sboisvert** [comment]
I can just stick this inside vip-go-mu-plugins in the utils where the other NR specific stuff is.
