### ISSUE TITLE
Events Store: improve handling of DB errors when race condition creates duplicates

### ISSUE THREAD

**Issue by ethitter** [Automattic/Cron-Control#147]
In rare cases, duplicate recurring events are created, and when the second event runs, its record will fail to update due to the unique constraints on the table. When `Events_Store::create_or_update_job()` triggers a "Duplicate entry 'X' for key 'ts_action_instance_status'" error, the store should better-recover from this state. It generally involves deleting duplicate events, or purging the entire queue, depending on size and the importance of the queue's contents.

**Comment by pySilver** [comment]
REPLACE INTO or ON DUPLICATE UPDATE might help here (or simply OOL with versioning)

**Comment by WPprodigy** [comment]
Tracking in #234
