### ISSUE TITLE
Perform graceful shutdown of the runner on SIGINT/SIGTERM

### ISSUE THREAD

**Issue by darthhexx** [Automattic/Cron-Control#152]
To ensure we don't leave things half done, we need to catch the signal, set a variable and then check it in our main loop for the exit condition.

**Comment by ethitter** [comment]
I added the option to disable execution to deal with this situation. It's a per-site option, but if one needed to shutdown all execution, one could filter the `a8c_cron_control_disable_run` to return `1`.

**Comment by darthhexx** [comment]
@ethitter what do you think of the PR #154 ? Seems to work as expected although I haven't tested it with an actual long running CLI job.
