### ISSUE TITLE
CLI: Make command names consistent with core

### ISSUE THREAD

**Issue by joshbetz** [Automattic/Cron-Control#153]
Core tends to use singular names (i.e. wp cron event), it might be good to change the command names to be consistent with that (i.e. wp cron-control events).

**Comment by ethitter** [comment]
I went with plurals for commands that operate predominantly on multiple things, mostly as a personal preference. `wp cron-control events list` seems more natural, for instance, than `wp cron-control event list`.

**Comment by joshbetz** [comment]
I'd tend to agree. I don't feel super strongly about it. On one hand, consistency with core wp-cli is nice (especially if you switch back and forth between the core cron command and cron-control often). On the other hand, I do agree `wp cron-control events` is more natural.

**Comment by simonwheatley** [comment]
Closing "won't fix"
