### ISSUE TITLE
Have the Cron Control Runner log in JSON

### ISSUE THREAD

**Issue by simonwheatley** [Automattic/Cron-Control#157]
The Cron Control runner should jog in JSON to make it easier to parse the logs into Logstash for searchability.

**Comment by hanifn** [comment]
@simonwheatley Is there a standard format for JSON log entries?

**Comment by simonwheatley** [comment]
@hanifn I suggest opening a Systems Request, and I’m happy to help formulate that just ping me on Slack

**Comment by hanifn** [comment]
@simonwheatley it appears there is a `standard` list of error log fields for logstash. Found [this](https://www.elastic.co/guide/en/logstash/current/field-extraction.html)

**Comment by ethitter** [comment]
For backcompat, the output format should be controlled via a flag. It might make sense to update the defaults to set that flag for new installs, but we shouldn't change the format without giving users a way back to the original output.

**Comment by hanifn** [comment]
@ethitter Agreed. A flag would be very useful to existing users.

**Comment by simonwheatley** [comment]
@joshbetz Chatting with @dchymko about monitoring WP-CLI, knowing when commands are cancelled, etc, and the related PR to this issue has been brought up as The Way To Do That. We wondered whether you would be able to take a look at shaping up the PR as part of this relay? 

This issue needs an estimate 😃

**Comment by joshbetz** [comment]
Yep, grabbing this from Hanif.
