### ISSUE TITLE
Problem with /etc/init.d/cron-control-runner

### ISSUE THREAD

**Issue by discoinfiltrator** [Automattic/Cron-Control#160]
I'm following the instructions here:

https://github.com/Automattic/Cron-Control/tree/master/runner

My OS is Debian 8.

I'm successfully running "env GOOS=linux make", and the binary is located in mu-plugins/cron-control/bin.  However, I'm running the other commands listed in the readme under "Installation", and am unable to run:

```
/etc/init.d/cron-control-runner start
```

Because the binary isn't located in /etc/init.d/. Any idea what I might be doing wrong?

**Comment by ethitter** [comment]
The init script (`init.sh`) is copied to `/etc/init.d`, not the runner itself. The init script's default location for the binary is `/usr/local/bin/cron-control-runner`, which you can override using the `defaults` file noted in step 3 of the readme you referenced. Once you've copied `defaults` to `/etc/default/cron-control-runner`, add `DAEMON=/path/to/your/binary` to that file, then update `/path/to/your/binary` accordingly.

**Comment by discoinfiltrator** [comment]
Ah, this must be a typo then:

```
Copy init.sh to /etc/init/cron-control-runner
```

I'll give this another shot and if all goes well I'll submit a PR with a change to the readme.

**Comment by ethitter** [comment]
Oh, indeed it is. Should be `/etc/init.d`, not `/etc/init`.

**Comment by discoinfiltrator** [comment]
Awesome, thanks.  So it seems to be installing properly now, but it doesn't end up running any tasks. 

My /etc/default/cron-control-runner file looks like:

```
DAEMON_ARGS="-workers-run 20 -workers-get 20 -wp /var/www/html/web/ -log /var/www/log.txt"
DAEMON=/var/www/html/web/wp-content/mu-plugins/cron-control/bin/cron-control-runner
```

The log file looks like it's trying to run tasks:

```
2018/03/28 15:03:18 runner.go:87: Starting with 20 event-retreival worker(s) and 20 event worker(s)
2018/03/28 15:03:18 runner.go:88: Retrieving events every 60 seconds
2018/03/28 15:03:18 runner.go:349: started event worker 20
2018/03/28 15:03:18 runner.go:349: started event worker 4
2018/03/28 15:03:18 runner.go:349: started event worker 1
2018/03/28 15:03:18 runner.go:349: started event worker 6
2018/03/28 15:03:18 runner.go:349: started event worker 5
2018/03/28 15:03:18 runner.go:349: started event worker 2
2018/03/28 15:03:18 runner.go:349: started event worker 7
2018/03/28 15:03:18 runner.go:301: started retriever 20
2018/03/28 15:03:18 runner.go:301: started retriever 12
2018/03/28 15:03:18 runner.go:301: started retriever 16
```

And my go version is:

```
go version go1.9.1 linux/amd64
```

I don't see anything in the readme files that could help me debug this further. Any idea what might be happening? I have an old python runner that executes wp-cli commands to run cron tasks, which is still running properly.

**Comment by ethitter** [comment]
There's a `-debug` flag that you can set via the `DAEMON_ARGS` option. I'm not sure why I omitted it from the readme. Running in debug mode should return a pretty detailed error message. 

The specific Go version isn't important, it only needs to be 1.8.3 or greater. 

I'd also caution that 20 runners and 20 workers are probably too many, unless you're dealing with a very large multisite and each site has many distinct events. Otherwise, most of those workers will sit idle and never be used. Cron Control curates the pending-events queue, and throwing additional runners/retrievers at it doesn't bypass the curation. The curation servers to purposes: to keep resource usage under control, and more importantly, to prevent running simultaneously two events with the same action, as neither WordPress nor most plugins are prepared for that.

**Comment by discoinfiltrator** [comment]
I just tried out the debug flag and the error I'm seeing is:

```
2018/03/28 17:22:57 runner.go:235: invalid character 'C' looking for beginning of value
2018/03/28 17:22:57 runner.go:264: Automatic execution disabled, sleeping for an additional 3 minutes
```

The code in question in runner.go is:

```
func getInstanceInfo() (siteInfo, error) {
	raw, err := runWpCliCmd([]string{"cron-control", "orchestrate", "runner-only", "get-info", "--format=json"})
	if err != nil {
		return siteInfo{}, err
	}

	jsonRes := make([]siteInfo, 0)
	if err = json.Unmarshal([]byte(raw), &jsonRes); err != nil {
		if debug {
			logger.Println(fmt.Sprintf("%+v", err))
		}

		return siteInfo{}, err
	}

	return jsonRes[0], nil
}
```

I can successfully run the command that this function is trying to run:

```
root@57c93f7a5393:/var/www# wp --path=/var/www/html/web/ --allow-root cron-control orchestrate runner-only get-info --format=json
[{"multisite":1,"siteurl":"http:\/\/local.bibliocms.com","disabled":0}]
```

Still investigating any config issues on my end, but sharing here in the meantime.

Much appreciated for the help btw.

**Comment by simonwheatley** [comment]
Closing this issue as there's no clear action.
