### ISSUE TITLE
Fix get_option() for tons of jobs

### ISSUE THREAD

**Issue by joshbetz** [Automattic/Cron-Control#163]
The public `Events_Store::get_option()` function gets exponentially slower as the jobs table grows. You can see in the example below that high offsets with low limits still look at all the rows.  The number of queries grows linearly with the number of pending jobs and the number of rows returned per query also grows linearly.

```
mysql> explain SELECT * FROM wp_a8c_cron_control_jobs WHERE status = 'pending' LIMIT 1600,100;
+------+-------------+--------------------------+------+---------------+--------+---------+-------+------+-----------------------+
| id   | select_type | table                    | type | possible_keys | key    | key_len | ref   | rows | Extra                 |
+------+-------------+--------------------------+------+---------------+--------+---------+-------+------+-----------------------+
|    1 | SIMPLE      | wp_a8c_cron_control_jobs | ref  | status        | status | 34      | const | 5413 | Using index condition |
+------+-------------+--------------------------+------+---------------+--------+---------+-------+------+-----------------------+
1 row in set (0.04 sec)
```

I think we could make an incremental improvement here by querying all the rows in 1 query with no limit. Better would be a high, but reasonable limit so we don't have to worry about ever returning 10000 rows, for example.

We could likely do even better by doing some math with the primary key. I'm thinking something like:

```
$id = SELECT ID FROM wp_a8c_cron_control_jobs WHERE `status` = 'pending' LIMIT 1;
$jobs = SELECT * FROM wp_a8c_cron_control_jobs WHERE `status` = 'pending' AND ID > $id AND ID < $id + 200 LIMIT 100; // Pad filter by 2x because we don't know how many complete jobs are in here
$next_id = $jobs[ length( $jobs ) - 1 ][ 'ID' ];
```

**Comment by ethitter** [comment]
Nice catch. Definitely suboptimal, and with the work done to make large queues cacheable, the low limit is almost certainly unnecessary at this point. As I recall, this is a holdover from the time when the posts table was used.
