### ISSUE TITLE
Filter future single actions

### ISSUE THREAD

**Issue by joshbetz** [Automattic/Cron-Control#167]
I don't think we ever check that single events are scheduled. We only need to know about them when they're going to run. If so, we can filter out single events that are more than about 5 minutes in the future.

**Comment by ethitter** [comment]
Be careful with this. At the least, when called as part of `wp_next_scheduled()`, all events need to be present or Core will enter a rescheduling loop.

When WP 5.0 lands, it provides new hooks that should greatly simplify how Cron Control hooks in, and this may not be necessary. I've been meaning to put together a branch using the new hooks from [#32656-core](https://core.trac.wordpress.org/ticket/32656).

**Comment by joshbetz** [comment]
I think this turns out to be not quite necessary right now. I'm going to close it and we can reopen if necessary.
