### ISSUE TITLE
Remove hardcoded limit in manage-event-lock CLI command

### ISSUE THREAD

**Issue by nickdaugherty** [Automattic/Cron-Control#172]
Currently the `manage-event-lock` CLI command displays a hardcoded maximum of `1`, but that should be hooked up to the constants / filters for that event.

https://github.com/Automattic/Cron-Control/blob/fd02cfbef233698c93ab9afb444d25b54a7a3fef/includes/wp-cli/class-lock.php#L49

**Comment by WPprodigy** [comment]
Can look into this during https://github.com/Automattic/Cron-Control/issues/233
