### ISSUE TITLE
Events: Use preflight filters added in WP 5.1

### ISSUE THREAD

**Issue by peterwilsoncc** [Automattic/Cron-Control#173]
**Task**
When setting and getting Cron jobs, make use of the new WP filters: `pre_schedule_event`, `pre_reschedule_event`, `pre_unschedule_event`, `pre_clear_scheduled_hook`, `pre_unschedule_hook`, `pre_get_scheduled_event`, `pre_next_scheduled` and `pre_get_ready_cron_jobs`.

**Background**
In WordPress 5.1, new filters will be added to preflight event scheduling to allow for custom Cron storage systems.

The filters were added in [WordPress#32656](https://core.trac.wordpress.org/ticket/32656) (see WordPress/wordpress-develop@a32ea2d35d2fcf7bccf54ff7abfad9a2b49ee360) and [WordPress#45797](https://core.trac.wordpress.org/ticket/45797) (see WordPress/wordpress-develop@0bc20594c78369a6778635cd58f2b90c57428d6d).

**Comment by WPprodigy** [comment]
Resolved in https://github.com/Automattic/Cron-Control/pull/219
