### ISSUE TITLE
Events: Detect duplicate events created with timestamps within two or three seconds

### ISSUE THREAD

**Issue by ethitter** [Automattic/Cron-Control#49]
When the plugin is activated under significant load, it's still possible for duplicate events to be created, despite what #12 and #19 do to address this. #19 has been effective for almost all cases, but there are still situations where a duplicate is created with a timestamp that is just a few seconds off, which isn't accounted for.

To avoid any further delay when rebuilding the cron array, either the job runner, or a new Internal Job, should be created to check events for "adjacent" timestamps.

**Comment by ethitter** [comment]
See also #52.

**Comment by ethitter** [comment]
#89 has largely proven this unnecessary. Most, if not all, duplication is now due to improper use of Core's cron functions (not calling `wp_next_scheduled()`, for example), rather than Cron Control's deficiencies. After #114 is in use for a period, we can revisit the need for this.

**Comment by WPprodigy** [comment]
Tracking in https://github.com/Automattic/Cron-Control/issues/234
